movie_project_/filmproject/filmproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("filmsapp.urls")),
]
if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie_project_/filmproject/filmsapp/urls.py
from django.urls import path
from .import views
app_name='filmsapp'
urlpatterns = [

    path('',views.key,name='key'),
    path('film/<int:film_id>/',views.details,name='details'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/', views.delete, name='delete')
]

movie_project_/filmproject/filmsapp/models.py
from django.db import models

# Create your models here.
class film(models.Model ):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='photos')

    def __str__(self):
        return self.name

movie_project_/filmproject/filmsapp/forms.py
from django import forms
from .models import film

class Movieform(forms.ModelForm):
    class Meta:
        model=film
        fields=['name','desc','year','img']

movie_project_/filmproject/filmsapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

# Create your views here.
from .models import film
from . forms import Movieform


def key(request):
    Film=film.objects.all()
    context={
        'film_list':Film
    }
    return render(request,'key.html',context)
def details(request, film_id):
    Film=film.objects.get(id=film_id)
    return render(request,"details.html",{'film':Film})

def add_movie(request):
    if request.method=="POST":
        name=request.POST.get('name',)
        desc = request.POST.get('desc', )
        year = request.POST.get('year', )
        img = request.FILES['img' ]
        movie=film(name=name,desc=desc,year=year,img=img)
        movie.save()

    return render(request,'add.html')
def update(request,id):
    movie=film.objects.get(id=id)
    form=Movieform(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})

def delete(request,id):
    if request.method=="POST":
        movie=film.objects.get(id=id)
        movie.delete()
        return  redirect('/')
    return render(request,'delete.html')

movie_project_/filmproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method ='POST' enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter your movie name"><br> <br>
    <input type="text" name="desc" placeholder="Enter your movie description"><br> <br>
    <input type="text" name="year" placeholder="Enter your movie year"><br> <br>
    <input type="file" name="img"><br> <br>
    <input type="submit">
</form>
{% endblock %}

movie_project_/filmproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MOVIE LISTS</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{%static 'style1.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
      FILM
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movie_project_/filmproject/templates/delete.html
<form method="POST">
  {% csrf_token %}
  do you want to delete the film ?
  <input type="submit">
</form>

movie_project_/filmproject/templates/details.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{film.img.url}}" width="200" height="250"><br>
        </div>

    <div class="col-md-6">
        <h4>{{film.name}}</h4>
        <h6>{{film.desc}}</h6>
        <h6>{{film.year}}</h6>
        <a class="btn btn-warning" href="{% url 'filmsapp:update' film.id %}">update</a>
        <a class="btn btn-danger" href="{% url 'filmsapp:delete' film.id %}">delete</a>

    </div>




    </div>
</div>
{% endblock %}

movie_project_/filmproject/templates/edit.html
<form method="POST"  enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

movie_project_/filmproject/templates/key.html
{% extends 'base.html' %}
{% block body %}


<div class="container">
    <div class="row">
        {% for i in film_list %}
        <div class="col-md-3">
            <div class="'card" style="width: 15rem;">
  <img src="{{i.img.url}}" class="card-img-top" alt="Card image cap" width="200px" height="200px;" >
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
      <div class="des">
    <p  class="card-text">{{i.desc}}</p>
          </div><br>
    <a href="{% url 'filmsapp:details' i.id %}" class="btn btn-primary">click here</a>
  </div>
</div>
        </div>
        {% endfor %}
    </div>

</div>



{% endblock %}